name: CI

env:
  CARGO_TERM_COLOR: always
  MSRV: '1.60'

on:
  push:
    branches:
    - main
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pwd:
          - .
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
        profile: minimal
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.pwd }}
        workspaces: ${{ matrix.pwd }}
    - name: Check
      working-directory: ${{ matrix.pwd }}
      run: |
        cargo clippy --all --all-targets --all-features
    - name: rustfmt
      working-directory: ${{ matrix.pwd }}
      run: |
        cargo fmt --all -- --check


